---
title: "AlexDoc"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(glmnet)
library(bnstruct)
```


```{r}
heart <- read.csv(file = 'heart.csv')
heart %>% 
  count(Cholesterol)
heart %>% 
  count(RestingBP)
heart %>% 
  count(Age)
heart %>% 
  count(MaxHR)
heart %>% 
  count(Oldpeak)
heart %>% 
  count(ST_Slope)
heart %>% 
  count(HeartDisease)
heart <- heart %>% 
  mutate(Sex = as.factor(Sex)) %>% 
  mutate(ChestPainType= as.factor(ChestPainType)) %>% 
  mutate(RestingECG= as.factor(RestingECG)) %>%
  mutate(ExerciseAngina = as.factor(ExerciseAngina)) %>%
  mutate(ST_Slope = as.factor(ST_Slope)) %>%
  mutate(HeartDisease = as.factor(HeartDisease)) 
#imputed <- knn.impute(as.matrix(heart),k = 10)
  
heart <- heart %>% 
  filter(Cholesterol != 0) %>% 
  filter(RestingBP!=0)
set.seed(1)
training <- sample(dim(heart)[1], 522)
train <- heart[training, ]
test <- heart[-training, ]
```

```{r}
x <- model.matrix(HeartDisease~., heart)[,-1]
y <- heart$HeartDisease
#Finding optimal lambda shrinkage value to reduce error through cross validation
set.seed(1)


cv.lasso <- cv.glmnet(x, y, alpha = 1, family = "binomial")
#Creation of lasso model and outputting regression coefficients
lasso_model <- glmnet(x, y, alpha = 1, family = "binomial",
lambda = cv.lasso$lambda.min)
coef(lasso_model)
```

```{r}

x <- model.matrix(HeartDisease~.^2, train)[,-1]
y <- train$HeartDisease
#Finding optimal lambda shrinkage value to reduce error through cross validation
set.seed(123)


cv.lasso <- cv.glmnet(x, y, alpha = 1, family = "binomial")
#Creation of lasso model and outputting regression coefficients
lasso_model <- glmnet(x, y, alpha = 1, family = "binomial",
lambda = cv.lasso$lambda.min)
coef(lasso_model)

```

```{r}
logistic_mod <- glm(HeartDisease ~ Sex + Age + ChestPainType + RestingBP + Oldpeak + FastingBS+ ST_Slope+ MaxHR + RestingECG + ExerciseAngina + Cholesterol +  Age*Sex + Age*ChestPainType + Age*RestingBP+ Age*Oldpeak+Sex*ChestPainType + Sex*FastingBS+ Sex*Oldpeak + Sex*ST_Slope+ ChestPainType*FastingBS+ ChestPainType*MaxHR + ChestPainType*RestingECG + ChestPainType*ExerciseAngina + ChestPainType*Oldpeak + ChestPainType*ST_Slope + RestingBP*Cholesterol + RestingBP*ExerciseAngina + RestingBP*Oldpeak + RestingBP*ST_Slope + Cholesterol*ExerciseAngina + FastingBS*RestingECG + FastingBS*ST_Slope + RestingECG*ST_Slope + ExerciseAngina*Oldpeak + ExerciseAngina*ST_Slope + Oldpeak*ST_Slope , family = "binomial", 
     data = train)

predprob <- predict(logistic_mod, test, type = "response")

preds <- c()
for(prob in predprob){
  if(prob>=.5){
    preds <- c(preds,1)
  }
  else{
    preds <- c(preds,0)
  }
}


wrong <- 0
for(i in 1:length(test$HeartDisease)){
  if(preds[i]!=test$HeartDisease[i]){
    wrong = wrong + 1
  }
}
print(wrong/length(test$HeartDisease))

```

