---
title: "Ensemble"
author: "Dani Trejo"
date: "12/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Downloading and prepping the data
```{r}
library(tidyverse)
library(patchwork)
library(randomForest)
library(pROC)
heart <- read.csv(file = 'heart.csv')
heart$HeartDisease <- factor(heart$HeartDisease)
#head(heart)

#test on 10%
heart <- heart %>% 
  mutate(Sex = as.factor(Sex)) %>% 
  mutate(ChestPainType= as.factor(ChestPainType)) %>% 
  mutate(RestingECG= as.factor(RestingECG)) %>%
  mutate(ExerciseAngina = as.factor(ExerciseAngina)) %>%
  mutate(ST_Slope = as.factor(ST_Slope)) %>%
  mutate(HeartDisease = as.factor(HeartDisease)) 
  
heart <- heart %>% 
  filter(Cholesterol != 0) %>% 
  filter(RestingBP!=0)

set.seed(1)
dt = sort(sample(nrow(heart), nrow(heart)*.9))
train<-heart[dt,]
test<-heart[-dt,]

x.train <- model.matrix(HeartDisease~., train)[,-1]
y.train <- train$HeartDisease

x.test <- model.matrix(HeartDisease~., test)[,-1]
y.test <- test$HeartDisease
```


### Fitting the Tree model
```{r}
set.seed(1)
rf.heart <- randomForest(HeartDisease ~ ., data = train, mtry = sqrt(11), ntree = 1000)
rf.heart
```

### Fitting the Logistic Regression from the Lasso
```{r}
set.seed(1)
logistic_mod <- glm(HeartDisease ~ Sex + Age + ChestPainType + RestingBP + Oldpeak + FastingBS+ ST_Slope+ MaxHR + RestingECG + ExerciseAngina + Cholesterol +  Age*Sex + Age*ChestPainType + Age*RestingBP+ Age*Oldpeak+Sex*ChestPainType + Sex*FastingBS+ Sex*Oldpeak + Sex*ST_Slope+ ChestPainType*FastingBS+ ChestPainType*MaxHR + ChestPainType*RestingECG + ChestPainType*ExerciseAngina + ChestPainType*Oldpeak + ChestPainType*ST_Slope + RestingBP*Cholesterol + RestingBP*ExerciseAngina + RestingBP*Oldpeak + RestingBP*ST_Slope + Cholesterol*ExerciseAngina + FastingBS*RestingECG + FastingBS*ST_Slope + RestingECG*ST_Slope + ExerciseAngina*Oldpeak + ExerciseAngina*ST_Slope + Oldpeak*ST_Slope , family = "binomial", 
     data = train)
```

### Fitting the SVM model
```{r}
set.seed(1)
#insert best svm here
```

## Calling predict on each model
```{r}
#Tree
tree.predictions <- predict(rf.heart, x.test)
print(tree.predictions)

#Logistic
log.predictions <- predict(logistic_mod, x.test, type = "response")
print(log.predictions)
```


### 
```{r}
wrong <- 0
for(i in 1:length(test$HeartDisease)){
  if(preds[i]!=test$HeartDisease[i]){
    wrong = wrong + 1
  }
}
print(wrong/length(test$HeartDisease))
```

