---
title: "svm"
output: pdf_document
---

```{r}
library(tidyverse)
library(stringr)
library(e1071)
```

```{r}
heart <- read.csv(file = 'heart.csv')
heart %>% 
  count(Cholesterol)
heart %>% 
  count(RestingBP)
heart %>% 
  count(Age)
heart %>% 
  count(MaxHR)
heart %>% 
  count(Oldpeak)
heart %>% 
  count(ST_Slope)
heart %>% 
  count(HeartDisease)
heart <- heart %>% 
  filter(Cholesterol != 0) %>% 
  filter(RestingBP!=0) %>% 
  mutate(Sex = as.factor(Sex)) %>% 
  mutate(ChestPainType= as.factor(ChestPainType)) %>% 
  mutate(RestingECG= as.factor(RestingECG)) %>%
  mutate(ExerciseAngina = as.factor(ExerciseAngina)) %>%
  mutate(ST_Slope = as.factor(ST_Slope)) %>%
  mutate(HeartDisease = as.factor(HeartDisease)) 

```

```{r}
set.seed(1)
x <- model.matrix(HeartDisease~., heart)[,-1]
y <- heart$HeartDisease
#x[y==1,] = x[y==1,] + 1
#plot(x, col = (3-y))

svmfit <- svm(y ~ ., data = heart, kernel = "linear", cost = 10, scale = FALSE)
summary(svmfit)
```


The code below creates a training and test data set.

```{r}
set.seed(1)
training <- sample(dim(heart)[1], 522)
train <- heart[training, ]
test <- heart[-training, ]
```

The code below fits a support vector classifier.

```{r}
svm.fit <- svm(HeartDisease ~., data = train, kernel = "linear", cost=0.01)
summary(svm.fit)
```
There are 720 Support Vectors.
```{r}
svm.pred <- predict(svm.fit, test)
wrong <- 0
for (i in 1:length(svm.pred)){
  if (svm.pred[i]!=test$HeartDisease[i]){
    wrong = wrong + 1
  }
}
print(wrong/length(test$HeartDisease))
```


